server:
  port: 8090

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    password: zfy123456
  redis:
    # Redis 单机单实例
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    # Redis 哨兵模式
    #    database: 1
    #    password: 123456
    #    sentinel:
    #      master: pat-master
    #      nodes: 172.16.206.128:26379,172.16.206.129:26379,172.16.206.130:26379
    # Redis 集群模式
#    password: 123456
#    cluster:
#      nodes: 172.16.206.191:6379,172.16.206.192:6379,172.16.206.193:6379,172.16.206.194:6379,172.16.206.195:6379,172.16.206.196:6379

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
